modLoader = "javafml"
loaderVersion = "[47,48)"
license = "MIT"
issueTrackerURL = "https://github.com/Sxilverrr/Quick-Craft/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/quick-craft"
logoFile = "logo.png"
authors = "Sxilverr"
description = '''Effortless instant autocrafting. Microcrafting is a thing of the past!'''

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "jei"
mandatory = false
versionRange = "[15,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${id}]]
modId = "emi"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
