org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-8.0.482.8-hotspot

mod_id=quickcraft
mod_name=Quick Craft
mod_version=2.1.0
mod_group=com.sxilverr.quickcraft

mc_version=1.12.2
forge_version=14.23.5.2847
mappings_version=stable_39

jei_file=3043174

projecte_file=2702991
ae2_file=2747063
rs_file=2940914
rs_addons_file=2941010
jer_file=2728585
ccl_file=2779848
avaritia_file=3143349
